-- Give user_profiles a surrogate id PK; demote telegram id to indexed tg_id.
-- Translate orders.taken_by and order_offers.user_id from tg_id to the new id.
BEGIN;

ALTER TABLE user_profiles RENAME COLUMN user_id TO tg_id;

-- IDENTITY backfills existing rows with 1..N and seeds the sequence.
ALTER TABLE user_profiles ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Translate references while both tg_id and id exist on user_profiles.
UPDATE orders o
   SET taken_by = up.id
  FROM user_profiles up
 WHERE o.taken_by = up.tg_id;

UPDATE order_offers oo
   SET user_id = up.id
  FROM user_profiles up
 WHERE oo.user_id = up.tg_id;

-- Clear references to users that no longer exist so FKs can be added.
DELETE FROM order_offers oo
 WHERE NOT EXISTS (SELECT 1 FROM user_profiles up WHERE up.id = oo.user_id);

UPDATE orders
   SET taken_by = NULL
 WHERE taken_by IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM user_profiles up WHERE up.id = orders.taken_by);

-- Swap PK tg_id -> id; keep tg_id unique, indexed and NOT NULL.
ALTER TABLE user_profiles DROP CONSTRAINT user_profiles_pkey;
ALTER TABLE user_profiles ALTER COLUMN tg_id SET NOT NULL;
ALTER TABLE user_profiles ADD PRIMARY KEY (id);
ALTER TABLE user_profiles ADD CONSTRAINT user_profiles_tg_id_key UNIQUE (tg_id);

-- The NOT NULL constraint was auto-named after the old user_id column; realign it.
ALTER TABLE user_profiles
    RENAME CONSTRAINT user_profiles_user_id_not_null TO user_profiles_tg_id_not_null;

-- Enforce "addressed by id" with real FKs.
ALTER TABLE order_offers
    ADD CONSTRAINT order_offers_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES user_profiles(id) ON DELETE CASCADE;

ALTER TABLE orders
    ADD CONSTRAINT orders_taken_by_fkey
    FOREIGN KEY (taken_by) REFERENCES user_profiles(id) ON DELETE SET NULL;

COMMIT;
