-- Standalone, FK-free transactions ledger replacing the user_profiles.balance
-- column as the single source of truth: balance = COALESCE(SUM(amount), 0).
-- Completion writes one flat row per credited line (one per pack size or per code),
-- so no row ever cascades from deletes elsewhere.

ALTER TABLE user_profiles DROP COLUMN balance;

DO $$ BEGIN
    CREATE TYPE transaction_kind AS ENUM ('pack', 'code');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS transactions (
    id          BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id  BIGINT           NOT NULL,
    order_id    INTEGER          NOT NULL,
    kind        transaction_kind NOT NULL,
    pack_size   INTEGER,
    code        TEXT,
    amount      NUMERIC(14, 2)   NOT NULL,
    created_at  TIMESTAMPTZ      NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS transactions_profile_created_idx
    ON transactions (profile_id, created_at);

CREATE INDEX IF NOT EXISTS transactions_profile_order_idx
    ON transactions (profile_id, order_id);
