-- Rewrite the ledger to one row per completed order. The old per-line rows
-- (one per pack size / per code) carried wrong money for code orders, so they
-- are dropped outright. Each order now stores its total in `amount` and the
-- pack/code breakdown in `details` JSONB (display only, never money math).
-- Reuses the existing transaction_kind enum from migration 015.

DROP TABLE IF EXISTS transactions;

CREATE TABLE transactions (
    id          BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id  BIGINT           NOT NULL,
    order_id    BIGINT           NOT NULL,
    kind        transaction_kind NOT NULL,
    amount      NUMERIC(14, 2)   NOT NULL,
    details     JSONB            NOT NULL,
    created_at  TIMESTAMPTZ      NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX transactions_profile_order_idx
    ON transactions (profile_id, order_id);

CREATE INDEX transactions_profile_created_idx
    ON transactions (profile_id, created_at);

-- Promote order identifiers from 32-bit INTEGER to BIGINT. orders.id is SERIAL, so
-- its owned sequence is widened too (SERIAL creates it AS integer). The
-- order_offers -> orders(id) FK is dropped and recreated because both sides of the
-- reference must change type together.
ALTER TABLE order_offers DROP CONSTRAINT order_offers_order_id_fkey;

ALTER TABLE orders ALTER COLUMN id TYPE BIGINT;
ALTER SEQUENCE orders_id_seq AS BIGINT;
ALTER TABLE orders ALTER COLUMN original_id TYPE BIGINT;
ALTER TABLE order_offers ALTER COLUMN order_id TYPE BIGINT;

ALTER TABLE order_offers
    ADD CONSTRAINT order_offers_order_id_fkey
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
